services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  nextjs:
    env_file:
      - .env
    build:
        context: .
        # Used while building the docker image for Prisma generation etc.
        args:
          - BUILD_DATABASE_URL=${BUILD_DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres